# Сборка Docker-контейнера для Yandex-Datasphere.
MAINTAINER Vladya

# Ставим систему из базовых инструкций Яндекса.

FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive

RUN useradd -ms /bin/bash --uid 1000 jupyter \
&& apt update \
&& apt install -y python3.9-dev python3.9-distutils curl \
&& ln -s /usr/bin/python3.9 /usr/local/bin/python3 \
&& curl https://bootstrap.pypa.io/get-pip.py | python3

# Обновляем сборщики пая.
RUN python3 -m pip install -U pip setuptools wheel

# Ставим загрузчик и компиляторы.
RUN apt install -y wget build-essential nasm yasm

# Скачиваем, собираем и ставим ffmpeg.
RUN wget -O ffmpeg.tar.xz https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/ffmpeg/7:5.1.2-3ubuntu1/ffmpeg_5.1.2.orig.tar.xz
RUN tar -xf ffmpeg.tar.xz
RUN cd /ffmpeg-5.1.2 && ./configure && make && make install
RUN rm -rf ffmpeg.tar.xz
RUN rm -rf ffmpeg-5.1.2/

# Обновляем PATH для корректной работы с Jupyter'ом.
ENV PATH=/home/jupyter/.local/bin:$PATH
